config/routes.rb
Phonebook::Application.routes.draw do
  get "welcome/index"

  resources :contacts
   root 'welcome#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :Name, presence: true,length: {minimum: 1}
	validates :Number,numericality: {only_integer: true}, length: {is: 10}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def index
		@contacts=Contact.all
	end

	def show
		@contact = Contact.find(params[:id])
	end

	def new
		@contact =Contact.new
	end

	def edit
		@contact=Contact.find(params[:id])
	end

	def create
		@contact =Contact.new(contact_params)
		

		if @contact.save
		    redirect_to @contact
		else
			render 'new'
		end
	end

	def update 
		@contact = Contact.find(params[:id])
		if @contact.update(contact_params)
			redirect_to @contact
		else
			render 'edit'
		end
	end

	def destroy
		@contact = Contact.find(params[:id])
		@contact.destroy
		redirect_to contacts_path
	end

	private
		def contact_params
			params.require(:contact).permit(:Name, :Number, :Email)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/_form.html.erb
<%= form_for @contact do |f|%>
<% if @contact.errors.any? %>
	<div id="error_explanation">
		<h2>
			<%= pluralize(@contact.errors.count, "error") %>
			prohibited this contact from being saved:
		</h2>
		<ul>
			<% @contact.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<%end%>
		</ul>
	</div>
<%end%>


<p>
				<%= f.label :Name %><br>
				<%= f.text_field :Name%>
			</p>

			<p>
				<%= f.label :Number %><br>
				<%= f.text_field :Number %>
			</p>

			<p>
				<%= f.label :Email %><br>
				<%= f.text_field :Email %>
			</p>

			<p>
				<%= f.submit %>
			</p>

		<% end %>

app/views/contacts/edit.html.erb
<h1>Edit Contact</h1>
<%= render 'form'%>
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h3>Contacts</h3>

<%= link_to 'New Contact', new_contact_path %>
<table>
	<tr>
		<th>Name</th>
		<th>Number</th>
		<th>Email</th>

	</tr>


		<% @contacts.each do |contact| %>
		<tr>
			<td><%= contact.Name %></td>
			<td><%= contact.Number %></td>
			<td><%= contact.Email %></td>
			<td><%= link_to 'Show',contact_path(contact)%></td>
			<td><%= link_to 'Edit',edit_contact_path(contact) %></td>
			<td><%= link_to 'Destroy',contact_path(contact),method: :delete,data: {confirm:'Do you want to proceed?'}%></td>
		</tr>
		<% end %>
</table>

app/views/contacts/new.html.erb
<h1> New Contact </h1>
<%= render 'form' %>
<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p>
	<strong>Name:</strong>
	<%= @contact.Name %>
</p>

<p>
	<strong>Number:</strong>
	<%= @contact.Number %>
</p>

<p>
	<strong>Email:</strong>
	<%= @contact.Email %>
</p>
<%= link_to 'Edit',edit_contact_path(@contact) %>
<%=link_to 'Back',contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Phonebook</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>My Phonebook</h1><br>




<%= link_to 'My contacts', controller: 'contacts' %>